### ISSUE TITLE
Generalize "array sized"

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-schemas#35]
"array sized" is an array with elements of a variable size. To know what type and size each element is, some field has to be read which indicates the type of an element. Therefore all elements must contain the same header with such a 'type' field.  The schema should be extended to be able to indicate what header is common to all elements and which field in that header indicates the type of the element.

Currently the yaml output that we have is this:

```yaml
  - comments: sub-transaction data (transactions are variable sized and payload size
      is in bytes)
    disposition: array sized
    name: transactions
    size: payload_size
    type: EmbeddedTransaction
```

Its not accurate that type is EmbeddedTransaction, its the header which contains the type of the array elements

Something like this would be better:

```yaml
  - comments: sub-transaction data (transactions are variable sized and payload size
      is in bytes)
    name: transactions
    size: payload_size
    type: array_sized EmbeddedTransaction  //<----- Header common to all elements in array
    header_type_field: type  //<----- Name of field in EmbeddedTransaction which contains type of element
```
