### ISSUE TITLE
Add enum for embedded transactions

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-schemas#36]
Right now embedded transactions have the same enum as normal transactions. To be able to distinguish between normal and embedded transactions we should generate enums for embedded transactions as well, like this:

```yaml
- comments: enumeration for embedded transaction types
  name: TransactionTypeEmbedded
  signedness: unsigned
  size: 2
  type: enum
  values:
  - comments: account key link transaction
    name: ACCOUNT_KEY_LINK
    value: 16716
  - comments: node key link transaction
    name: NODE_KEY_LINK
    value: 16972
  - comments: voting key link transaction
    name: VOTING_KEY_LINK
    value: 16707
  - comments: vrf key link transaction
    name: VRF_KEY_LINK
    value: 16963
  - comments: hash lock transaction
    name: HASH_LOCK
    value: 16712
  - comments: secret lock transaction
    name: SECRET_LOCK
    value: 16722
  - comments: secret proof transaction
    name: SECRET_PROOF
    value: 16978
  - comments: account metadata transaction
    name: ACCOUNT_METADATA
    value: 16708
  - comments: mosaic metadata transaction
    name: MOSAIC_METADATA
    value: 16964
  - comments: namespace metadata transaction
    name: NAMESPACE_METADATA
    value: 17220
  - comments: mosaic definition transaction
    name: MOSAIC_DEFINITION
    value: 16717
  - comments: mosaic supply change transaction
    name: MOSAIC_SUPPLY_CHANGE
    value: 16973
  - comments: multisig account modification transaction
    name: MULTISIG_ACCOUNT_MODIFICATION
    value: 16725
  - comments: address alias transaction
    name: ADDRESS_ALIAS
    value: 16974
  - comments: mosaic alias transaction
    name: MOSAIC_ALIAS
    value: 17230
  - comments: namespace registration transaction
    name: NAMESPACE_REGISTRATION
    value: 16718
  - comments: account address restriction transaction
    name: ACCOUNT_ADDRESS_RESTRICTION
    value: 16720
  - comments: account mosaic restriction transaction
    name: ACCOUNT_MOSAIC_RESTRICTION
    value: 16976
  - comments: account operation restriction transaction
    name: ACCOUNT_OPERATION_RESTRICTION
    value: 17232
  - comments: mosaic address restriction transaction
    name: MOSAIC_ADDRESS_RESTRICTION
    value: 16977
  - comments: mosaic global restriction transaction
    name: MOSAIC_GLOBAL_RESTRICTION
    value: 16721
  - comments: transfer transaction
    name: TRANSFER
    value: 16724
```
(note that the aggregate transactions (complete and bonded) are not included)

Even though the individual enum values are the same for both normal and embedded transactions we need it for when deserializing "array sized" arrays.
