### ISSUE TITLE
Add support for adding enum type values for structs

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-schemas#37]
Right now there is no way to say what enum type a struct is. We are implicitly using const for that now like this:

```yaml
- comments: binary layout for a non-embedded mosaic definition transaction
  layout:
  - comments: ""
    disposition: const
    name: TRANSACTION_VERSION
    signedness: unsigned
    size: 1
    type: byte
    value: 1
  - comments: ""
    disposition: const
    name: TRANSACTION_TYPE
    type: TransactionType
    value: MOSAIC_DEFINITION
  - comments: ""
    disposition: inline
    type: Transaction
  - comments: ""
    disposition: inline
    type: MosaicDefinitionTransactionBody
  name: MosaicDefinitionTransaction
  type: struct
```

But we should make it explicit. For example, something like this for normal transactions:

```yaml
  - comments: ""
    disposition: type
    type: TransactionType
    value: MOSAIC_DEFINITION
```

and this for embedded transactions:

```yaml
  - comments: ""
    disposition: type
    type: TransactionTypeEmbedded
    value: MOSAIC_DEFINITION
```
